### ISSUE TITLE
redirect http://provenanceweb.org/formats to http://provenanceweb.tw.rpi.edu/formats

### ISSUE THREAD

**Issue by timrdf** [timrdf/provenanceweb#2]
IW group agreed to use http://provenanceweb.org as its namespace for ontology, registry, and some application instance data.

The TWC development infrastructure uses VMs on aquarius. We have a VM on aquarius for provenance web, and is available at http://provenanceweb.tw.rpi.edu

We need to redirect [the linked data] portions of http://provenanceweb.org into http://provenanceweb.tw.rpi.edu to leverage Prizms data. Right now, that is FileFormats instances.

e.g. 
- http://provenanceweb.org/format/mime/application/gzip can land onto http://provenanceweb.tw.rpi.edu/format/mime/application/gzip (the latter will resolve once Tim gets LODSPeaKr to mirror URIs).
- http://provenanceweb.org/formats/pronom/x-fmt/266 -> http://provenanceweb.tw.rpi.edu/formats/pronom/x-fmt/266

So, Tim needs Cynthia to redirect all URIs under `http://provenanceweb.org/format` to `http://provenanceweb.tw.rpi.edu/format`

Tim _thinks_ this is similar to how we're mapping http://provenanceweb.org/ns/pml# to https://github.com/timrdf/pml/blob/master/ontology/pml-3.0.owl

**Comment by csccsrpi** [comment]
provenenceweb.org now points to provenenceweb.tw.rpi.edu instead of provenace.rpi.edu .

**Comment by timrdf** [comment]
http://tw.rpi.edu/web/inside/machine/aquarius#provenanceweb

**Comment by csccsrpi** [comment]
Hi Tim,

This page: http://tw.rpi.edu/web/inside/machine/inference-web.org/wiki/Main_Page
says not found.

Need to add a redirect?

Thanks,

csc
